Mayhem Integration
mayhemheroes/tokei pull request #1
Opened 2022-05-09 02:01 UTC by Gediminas19

2022-05-09 21:23 UTC, xansec requested changes
Unless you have changed the libraries/crates that the project is using, I would recommend not committing your `Cargo.lock` file. Please remove.

2022-05-09 21:23 UTC, xansec commented on mayhem/Dockerfile
> +# Set to fuzz!
Is it possible to copy your targets from this build stage into a separate stage, to reduce image size?

2022-05-29 21:22 UTC, xansec commented
Please make the above requested changes, or we will have to close this PR

2022-05-29 22:13 UTC, Gediminas19 commented
Sorry, I'll do it tonight

2022-05-31 02:28 UTC, xansec commented
It looks like the `Cargo.lock` changes are still in this PR. My guess is that since you've updated them, they're now tracking changes in this branch. You might want to create a new PR with only the 4 files you are interested in committing (you could create a new branch) and then create a PR with that new branch.

2022-05-31 03:12 UTC, xansec commented
Awesome, LGTM!

2022-05-31 03:13 UTC, merged